<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
    body { font-family: 'DejaVu Sans', sans-serif; font-size: 11px; color: #1e1f24; }
    .header { text-align:center; margin-bottom:20px; border-bottom:2px solid #4f46e5; padding-bottom:12px; }
    .header h1 { font-size:20px; color:#4f46e5; margin:0; }
    .header p { font-size:10px; color:#6b7280; margin:4px 0 0; }

    .section-title { font-size:14px; font-weight:bold; color:#1e1f24; margin:22px 0 10px; border-left:4px solid #4f46e5; padding-left:8px; }

    .stats-grid { width:100%; border-collapse:collapse; margin-bottom:10px; }
    .stats-grid td { width:25%; padding:10px; text-align:center; border:1px solid #e2e8f0; }
    .stats-num { font-size:18px; font-weight:bold; color:#4f46e5; display:block; }
    .stats-label { font-size:9px; color:#6b7280; text-transform:uppercase; }

    table.data-table { width:100%; border-collapse:collapse; margin-bottom:10px; }
    table.data-table th { background:#f8fafc; color:#64748b; font-size:9px; text-transform:uppercase; padding:6px 8px; border-bottom:1.5px solid #e2e8f0; text-align:left; }
    table.data-table td { padding:6px 8px; border-bottom:1px solid #f1f5f9; font-size:9.5px; }

    .badge { padding:2px 6px; border-radius:4px; font-size:8.5px; font-weight:bold; }
    .badge-active { background:#f0fdf4; color:#16a34a; }
    .badge-suspended { background:#fff7ed; color:#ea580c; }
    .badge-banned { background:#fef2f2; color:#dc2626; }

    .footer { text-align:center; font-size:9px; color:#9ca3af; margin-top:25px; border-top:1px solid #e2e8f0; padding-top:8px; }
    .page-break { page-break-before: always; }
</style>
</head>
<body>

<div class="header">
    <h1>Borobhai.online — Admin Report</h1>
    <p>Generated by {{ $generatedBy }} on {{ $generated->format('d M Y, g:i a') }}</p>
</div>

{{-- ===== SUMMARY ===== --}}
<div class="section-title">Summary</div>
<table class="stats-grid">
    <tr>
        <td><span class="stats-num">{{ $counters['total_users'] }}</span><span class="stats-label">Total Users</span></td>
        <td><span class="stats-num">{{ $counters['total_students'] }}</span><span class="stats-label">Students</span></td>
        <td><span class="stats-num">{{ $counters['total_alumni'] }}</span><span class="stats-label">Alumni</span></td>
        <td><span class="stats-num">{{ $counters['total_teachers'] }}</span><span class="stats-label">Teachers</span></td>
    </tr>
    <tr>
        <td><span class="stats-num">{{ $counters['total_circulars'] }}</span><span class="stats-label">Job Circulars</span></td>
        <td><span class="stats-num">{{ $counters['pending_reports'] }}</span><span class="stats-label">Pending Reports</span></td>
        <td><span class="stats-num">{{ $counters['resolved_reports'] }}</span><span class="stats-label">Resolved Reports</span></td>
        <td><span class="stats-num">{{ $counters['suspended_temp'] + $counters['suspended_perm'] }}</span><span class="stats-label">Suspended Users</span></td>
    </tr>
</table>

{{-- ===== USERS ===== --}}
<div class="section-title">User List ({{ $users->count() }})</div>
<table class="data-table">
    <thead>
        <tr>
            <th style="width:5%;">#</th>
            <th style="width:25%;">Name</th>
            <th style="width:28%;">Email</th>
            <th style="width:14%;">Role</th>
            <th style="width:14%;">Status</th>
            <th style="width:14%;">Joined</th>
        </tr>
    </thead>
    <tbody>
    @foreach($users as $u)
        <tr>
            <td>{{ $loop->iteration }}</td>
            <td>{{ $u->name }}</td>
            <td>{{ $u->email }}</td>
            <td>{{ ucfirst($u->role) }}</td>
            <td>
                @if($u->status === 'suspended_temp')
                    <span class="badge badge-suspended">7d Suspended</span>
                @elseif($u->status === 'suspended_perm')
                    <span class="badge badge-banned">Banned</span>
                @else
                    <span class="badge badge-active">Active</span>
                @endif
            </td>
            <td>{{ $u->created_at->format('d M Y') }}</td>
        </tr>
    @endforeach
    </tbody>
</table>

{{-- ===== REPORT HISTORY ===== --}}
<div class="page-break"></div>
<div class="section-title">Report History ({{ $reportHistory->count() }})</div>
<table class="data-table">
    <thead>
        <tr>
            <th style="width:5%;">#</th>
            <th style="width:10%;">Type</th>
            <th style="width:25%;">Content</th>
            <th style="width:13%;">Reason</th>
            <th style="width:22%;">Final Outcome</th>
            <th style="width:12%;">Resolved At</th>
            <th style="width:13%;">Appeal</th>
        </tr>
    </thead>
    <tbody>
    @forelse($reportHistory as $r)
        <tr>
            <td>{{ $loop->iteration }}</td>
            <td>{{ ucfirst($r->type) }}</td>
            <td>{{ $r->targetTitle }}</td>
            <td>{{ ucfirst($r->reason) }}</td>
            <td>
                @if($r->appeal_status === 'reviewed')
                    Appeal Approved — Restored
                @elseif($r->action_taken === 'deleted')
                    Content Removed
                @elseif($r->action_taken === 'dismissed_no_violation')
                    Dismissed — No Violation
                @else
                    Marked Resolved
                @endif
                @if($r->was_warned) <br><span style="color:#d97706;">(User was also warned)</span> @endif
            </td>
            <td>{{ $r->updated_at->format('d M Y') }}</td>
            <td>
                @if($r->appeal_status === 'reviewed') Approved
                @elseif($r->appeal_status === 'ignored') Ignored
                @else — @endif
            </td>
        </tr>
    @empty
        <tr><td colspan="7" style="text-align:center;color:#9ca3af;">No resolved reports yet.</td></tr>
    @endforelse
    </tbody>
</table>

<div class="footer">
    Borobhai.online Admin Panel — Confidential Internal Report
</div>

</body>
</html>